# Generated by Django 5.0.6 on 2026-01-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('shop', '0012_tenant_business_type_alter_tenant_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Combo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Combo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='combo_images/', verbose_name='Imagem do Combo')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='shop.tenant')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComboSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverycategory', verbose_name='Categoria Permitida')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='delivery.combo')),
            ],
            options={
                'verbose_name': 'Opção do Combo',
                'verbose_name_plural': 'Opções do Combo',
            },
        ),
    ]
