# Generated by Django 5.0.6 on 2026-01-05 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_combo_comboslot'),
        ('shop', '0012_tenant_business_type_alter_tenant_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('customer_whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Endereço de Entrega')),
                ('payment_method', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão de Crédito/Débito'), ('pix', 'PIX')], max_length=20, verbose_name='Forma de Pagamento')),
                ('change_for', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco para')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('items_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total dos Itens')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa de Entrega')),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Final')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('on_the_way', 'Saiu para Entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryzone', verbose_name='Bairro')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='shop.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.deliveryorder')),
            ],
        ),
    ]
