# Generated by Django 5.0.6 on 2026-01-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryorder_deliveryorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderitem',
            name='original_cart_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
