# Generated by Django 5.0.6 on 2026-01-13 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryorderitem_original_cart_key'),
        ('shop', '0012_tenant_business_type_alter_tenant_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOptional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Opcional')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Adicional')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionals', to='delivery.deliverycategory', verbose_name='Categoria')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tenant')),
            ],
            options={
                'verbose_name': 'Opcional',
                'verbose_name_plural': 'Opcionais',
            },
        ),
    ]
