# Generated by Django 5.0.6 on 2026-01-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliveryoptional'),
        ('shop', '0013_tenant_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOnlineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_online/', verbose_name='Imagem do Cardápio')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_online_images', to='shop.tenant')),
            ],
            options={
                'verbose_name': 'Imagem do Cardápio Online',
                'verbose_name_plural': 'Imagens do Cardápio Online',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
