# Generated by Django 5.0.6 on 2026-01-30 00:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_menuonlineimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
    ]
