# Generated by Django 5.0.6 on 2026-02-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_deliveryorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
