# Generated by Django 5.0.6 on 2025-11-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='category',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Defina campos extras para esta categoria em formato JSON.'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
