# Generated by Django 5.0.6 on 2025-12-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para a URL da vitrine.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='extra_fields',
            field=models.JSONField(blank=True, default=list, help_text='Defina campos extras para esta categoria em formato JSON.'),
        ),
    ]
