# Generated by Django 5.0.6 on 2025-12-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_tenant_slug_alter_category_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payment_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave da API'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('mercadopago', 'Mercado Pago'), ('pagseguro', 'PagSeguro')], max_length=20, null=True, verbose_name='Gateway de Pagamento'),
        ),
    ]
