# Generated by Django 5.0.6 on 2025-12-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_tenant_payment_api_key_tenant_payment_gateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='payment_api_key',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='payment_gateway',
        ),
        migrations.AddField(
            model_name='tenant',
            name='mercadopago_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave da API do Mercado Pago'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pagseguro_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave da API do PagSeguro'),
        ),
    ]
