# Generated by Django 5.0.6 on 2026-01-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='display_order',
            field=models.CharField(choices=[('newest', 'Mais Recentes'), ('price_asc', 'Menor Preço'), ('price_desc', 'Maior Preço'), ('name', 'Nome (A-Z)'), ('category', 'Categoria')], default='newest', max_length=20, verbose_name='Ordenação Padrão da Vitrine'),
        ),
    ]
