# Generated by Django 5.0.6 on 2026-01-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_tenant_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='Logo da Loja'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='promotion_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Categoria de Promoção em Destaque'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp para Contato'),
        ),
    ]
