# Generated by Django 5.0.6 on 2026-01-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_tenant_logo_tenant_promotion_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('ecommerce', 'E-commerce (Varejo)'), ('delivery', 'Delivery (Restaurantes/Bebidas)')], default='ecommerce', max_length=20, verbose_name='Área de Atuação'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='display_order',
            field=models.CharField(choices=[('category', 'Padrão (Por Categoria)'), ('price_asc', 'Menor Preço'), ('price_desc', 'Maior Preço')], default='newest', max_length=20, verbose_name='Ordenação Padrão da Vitrine'),
        ),
    ]
