# Generated by Django 5.0.6 on 2026-01-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_tenant_business_type_alter_tenant_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Loja Aberta'),
        ),
    ]
