# Generated by Django 5.0.6 on 2026-01-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_tenant_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('ecommerce', 'E-commerce (Varejo)'), ('delivery', 'Delivery (Restaurantes/Bebidas)'), ('bar', 'Bar (Bebidas e Serviços)')], default='ecommerce', max_length=20, verbose_name='Área de Atuação'),
        ),
    ]
