# Generated by Django 5.0.6 on 2026-01-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_tenant_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='numero_mesas',
            field=models.PositiveIntegerField(default=10, help_text='Quantidade de mesas disponíveis no bar', verbose_name='Número de Mesas'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='permitir_gorjeta_10',
            field=models.BooleanField(default=False, help_text='Permitir que clientes adicionem 10% de gorjeta opcional', verbose_name='Permitir Gorjeta 10%'),
        ),
    ]
