# Generated by Django 5.0.6 on 2026-01-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_tenant_numero_mesas_tenant_permitir_gorjeta_10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='permitir_gorjeta_10',
            field=models.BooleanField(default=False, help_text='Permitir que clientes adicionem 10% de taxa de serviço opcional', verbose_name='Permitir Taxa 10% Serviço'),
        ),
    ]
