# Generated by Django 5.0.6 on 2026-02-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_tenant_permitir_gorjeta_10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('ecommerce', 'E-commerce (Varejo)'), ('delivery', 'Delivery (Restaurantes/Bebidas)'), ('bar', 'Bar (Bebidas e Serviços)'), ('bar_delivery', 'Bar & Delivery (Híbrido)')], default='ecommerce', max_length=20, verbose_name='Área de Atuação'),
        ),
    ]
