# Generated by Django 5.0.6 on 2026-01-26 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0013_tenant_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_categories', to='shop.tenant')),
            ],
            options={
                'verbose_name': 'Categoria do Bar',
                'verbose_name_plural': 'Categorias do Bar',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BarMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Item')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bar_menu_items/', verbose_name='Imagem')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bar.barcategory', verbose_name='Categoria')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_menu_items', to='shop.tenant')),
            ],
            options={
                'verbose_name': 'Item do Bar',
                'verbose_name_plural': 'Itens do Bar',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BarZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa de Serviço (R$)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_zones', to='shop.tenant')),
            ],
            options={
                'verbose_name': 'Zona do Bar',
                'verbose_name_plural': 'Zonas do Bar',
            },
        ),
    ]
