# Generated by Django 5.0.6 on 2026-01-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
        ('shop', '0015_tenant_numero_mesas_tenant_permitir_gorjeta_10'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.PositiveIntegerField(verbose_name='Número da Mesa')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('paga', 'Paga')], default='aberta', max_length=10, verbose_name='Status')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('gorjeta_10', models.BooleanField(default=False, verbose_name='Gorjeta 10%')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_comandas', to='shop.tenant')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-data_abertura'],
                'unique_together': {('tenant', 'numero_mesa', 'status')},
            },
        ),
        migrations.CreateModel(
            name='BarComandaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='bar.barcomanda')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.barmenuitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item da Comanda',
                'verbose_name_plural': 'Itens da Comanda',
            },
        ),
    ]
