# Generated by Django 5.0.6 on 2026-01-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_barcomanda_barcomandaitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barcomanda',
            unique_together=set(),
        ),
    ]
