# Generated by Django 5.0.6 on 2026-01-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_remove_unique_together_barcomanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barmenuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='barmenuitem',
            name='image',
        ),
        migrations.AlterField(
            model_name='barcomanda',
            name='gorjeta_10',
            field=models.BooleanField(default=False, verbose_name='Taxa 10% Serviço'),
        ),
    ]
