# Generated by Django 5.0.6 on 2026-02-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_remove_description_image_from_barmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarSystemNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Texto do Aviso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aviso do Sistema (Bar)',
                'verbose_name_plural': 'Avisos do Sistema (Bar)',
                'ordering': ['-created_at'],
            },
        ),
    ]
